source "azure-arm" "autogenerated_1" {
    //use_interactive_auth = true
  async_resourcegroup_delete = true
  azure_tags = {
    dept = "Engineering"
    task = "Image deployment"
  }
  client_id                         = "5ca79de7-882b-42df-87ed-cb7510ac4858"
  client_secret                     = "Mc88Q~6QbAeL31aj8MCjfP.1lvWNBT3-LFKsGbLq"
  subscription_id                   = "333abe86-07db-49d7-b9bc-1c998528c473"
  tenant_id                         = "883ed05e-4578-4c0b-8bfc-66b47663e07c"

  managed_image_name                = "myPackerImage2"
  managed_image_resource_group_name = "myPackerImages"

  os_type                           = "Linux"
  image_publisher                   = "Canonical"
  image_offer                       = "UbuntuServer"
  image_sku                         = "18.04-LTS"

  location                          = "West Europe"
  vm_size                           = "Standard_B1ls"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]
  
  provisioner "shell" {
    //script          = "./init-script.sh"
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    inline = [
      "apt-get update",
      "apt-get upgrade -y",
      "apt-get -y install nginx",
      "mkdir /src"
    ]
  }
  
/*   provisioner "file" {
    source      = "./demo-1.0.0-SNAPSHOT.jar"
    destination = "/src/demo-1.0.0-SNAPSHOT.jar"
  } */

}